source 'https://rubygems.org'

gem 'devise', '~> 4.1.1'
gem 'devise-i18n'
gem 'jquery-rails'
gem 'rails', '~> 4.2.6'
gem 'rails_12factor'
gem 'russian'
gem 'twitter-bootstrap-rails'
gem 'uglifier', '>= 1.3.0'

# Гем для загрузки картинок
gem 'carrierwave'

# Гем для обработки картинок
gem 'rmagick'

# Гем для работы carrierwave с хранилищем Amazon S3
gem 'fog-aws'

group :production do
  gem 'pg'
end

group :development, :test do
  gem 'byebug'
  gem 'sqlite3'
end
